import cerbose
from cerbose import cprint, mprint, cquery, cyn

cprint("none", "I like frogs.")
cprint("ok", "I like frogs.")
cprint("note", "I like frogs.")
cprint("warn", "I like frogs.")
cprint("error", "I like frogs.")
cprint("debug", "I like frogs.")
cprint("info", "I like frogs.")
cprint("query", "I like frogs.")
cprint("input", "I like frogs.")
cprint("load", "I like frogs.")
cprint("pause", "I like frogs.")
cprint("stat", f"{cerbose.cerbar(20, 70, 42)} I like frogs.")
cprint("fatal", "I like frogs.")
cprint("trace", "I like frogs.")
cprint("proc", "I like frogs.")
cprint("rege", "Repeat explained in README/docs. I still like frogs.")
cprint("info", "Double tag test. I still like frogs.", subtag="debug")
cprint("debug", "Text colour test. I still like frogs.", text_colour="yellow")
cprint("debug", "Timestamp test. I still like frogs.", timestamp=True)
cerbose.reset_align()
mprint("warn", "Multi-line test.\nI still like frogs.")
inp = cquery('query', 'Give feedback on the frogs.', '*', subtag='warn')
cprint("info", f"You typed {inp}!")
inp = cyn('query', 'So, would you say you like frogs?')
cprint("info", f"Nice!")
